# This work is subject to the CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
# license. Its contents can be found at:
# http://creativecommons.org/publicdomain/zero/1.0/

all:
	make -C simplewindow
	make -C draw
	make -C fsaa
	make -C nehe03
	make -C nehe04
	make -C nehe05
	make -C nehe06
	make -C nehe07
	make -C nehe08

clean:
	make -C simplewindow clean
	make -C draw clean
	make -C fsaa clean
	make -C nehe03 clean
	make -C nehe04 clean
	make -C nehe05 clean
	make -C nehe06 clean
	make -C nehe07 clean
	make -C nehe08 clean
